const CFG={calendarId:process.env.GOOGLE_CALENDAR_ID||'primary',tz:process.env.GOOGLE_CALENDAR_TIMEZONE||'America/Sao_Paulo',start:+(process.env.MEETING_START_HOUR||9),end:+(process.env.MEETING_END_HOUR||18),duration:+(process.env.MEETING_DURATION_MINUTES||30),step:+(process.env.MEETING_SLOT_STEP_MINUTES||30),lead:+(process.env.MEETING_MIN_LEAD_MINUTES||120),days:+(process.env.MEETING_HORIZON_DAYS||30),support:process.env.SUPPORT_EMAIL||'contato@agencia03m.com.br'};
const limits=globalThis.__m03Limits||new Map();globalThis.__m03Limits=limits;
const clean=(v,n=300)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,n);
const emailOk=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const tzOk=z=>{try{new Intl.DateTimeFormat('en-US',{timeZone:z}).format();return true}catch{return false}};
const dateOk=d=>/^\d{4}-\d{2}-\d{2}$/.test(d);
const parts=(d,z)=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:z,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',weekday:'short',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
const offset=(d,z)=>{const p=parts(d,z);return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-d.getTime()};
function zoned(date,time,z){const [y,m,d]=date.split('-').map(Number),[h,mi]=time.split(':').map(Number),wall=new Date(Date.UTC(y,m-1,d,h,mi));let r=new Date(wall-offset(wall,z));return new Date(wall-offset(r,z))}
function addDay(s){const[y,m,d]=s.split('-').map(Number);return new Date(Date.UTC(y,m-1,d+1)).toISOString().slice(0,10)}
async function token(){const {GOOGLE_CLIENT_ID:id,GOOGLE_CLIENT_SECRET:secret,GOOGLE_REFRESH_TOKEN:refresh}=process.env;if(!id||!secret||!refresh)throw Object.assign(new Error('Online scheduling is being configured.'),{code:'CONFIG'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refresh,grant_type:'refresh_token'})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw new Error('Google Calendar connection failed.');return j.access_token}
async function google(path,opt={}){const t=await token(),r=await fetch('https://www.googleapis.com/calendar/v3'+path,{...opt,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok){console.error('Google Calendar',r.status,JSON.stringify(j).slice(0,500));throw new Error(j?.error?.message||'Google Calendar request failed.')}return j}
async function busy(a,b){const j=await google('/freeBusy',{method:'POST',body:JSON.stringify({timeMin:a.toISOString(),timeMax:b.toISOString(),timeZone:CFG.tz,items:[{id:CFG.calendarId}]})});return j?.calendars?.[CFG.calendarId]?.busy||Object.values(j?.calendars||{})[0]?.busy||[]}
const collides=(a,b,list)=>list.some(x=>a.getTime()<Date.parse(x.end)&&b.getTime()>Date.parse(x.start));
function allowed(a,b){const p=parts(a,CFG.tz),mins=+p.hour*60 + +p.minute;if(['Sat','Sun'].includes(p.weekday))return false;if(mins<CFG.start*60||mins+CFG.duration>CFG.end*60)return false;if((mins-CFG.start*60)%CFG.step!==0)return false;const now=Date.now();return a.getTime()>=now+CFG.lead*60000&&a.getTime()<=now+CFG.days*86400000&&b>a}
async function availability(date,z){const a=zoned(date,'00:00',z),b=zoned(addDay(date),'00:00',z),taken=await busy(a,b),slots=[];for(let ms=a.getTime();ms<b.getTime();ms+=15*60000){const s=new Date(ms),e=new Date(ms+CFG.duration*60000);if(allowed(s,e)&&!collides(s,e,taken))slots.push({start:s.toISOString(),end:e.toISOString()})}return slots}
function limited(req){const ip=clean((req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0],100),now=Date.now(),arr=(limits.get(ip)||[]).filter(x=>now-x<600000);if(arr.length>=20){limits.set(ip,arr);return true}arr.push(now);limits.set(ip,arr);return false}
function url(v){try{const u=new URL(/^https?:\/\//i.test(v)?v:`https://${v}`);return ['http:','https:'].includes(u.protocol)&&u.hostname.includes('.')?u.href:null}catch{return null}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');if(limited(req))return res.status(429).json({error:'Too many requests. Please try again later.'});try{
if(req.method==='GET'){const date=clean(req.query?.date,10),z=clean(req.query?.timeZone,100);if(!dateOk(date)||!tzOk(z))return res.status(400).json({error:'Invalid date or timezone.'});return res.status(200).json({slots:await availability(date,z),durationMinutes:CFG.duration,supportEmail:CFG.support});}
if(req.method!=='POST'){res.setHeader('Allow','GET, POST');return res.status(405).json({error:'Method not allowed.'});}
const b=req.body||{};if(clean(b.website_confirm,100))return res.status(200).json({ok:true});const website=url(clean(b.website,500)),firstName=clean(b.firstName,80),email=clean(b.email,160).toLowerCase(),company=clean(b.company,120),phone=clean(b.phone,40),start=new Date(clean(b.meetingStart,80)),visitorTimeZone=clean(b.visitorTimeZone,100);if(!website||firstName.length<2||!emailOk(email)||!Number.isFinite(start.getTime())||!tzOk(visitorTimeZone))return res.status(400).json({error:'Please complete the required fields and choose an available time.'});const end=new Date(start.getTime()+CFG.duration*60000);if(!allowed(start,end)||collides(start,end,await busy(start,end)))return res.status(409).json({error:'That time is no longer available. Please choose another slot.'});const host=(()=>{try{return new URL(website).hostname}catch{return website}})();const event={summary:`03M AI Visibility Audit — ${company||host}`,description:[`AI Visibility Audit meeting booked from the Agência 03M U.S. website.`,``,`Name: ${firstName}`,`Email: ${email}`,`Company: ${company||'Not provided'}`,`Phone: ${phone||'Not provided'}`,`Website: ${website}`,`Visitor timezone: ${visitorTimeZone}`,``,`Questions: ${CFG.support}`].join('\n'),start:{dateTime:start.toISOString(),timeZone:CFG.tz},end:{dateTime:end.toISOString(),timeZone:CFG.tz},attendees:[{email}],conferenceData:{createRequest:{requestId:crypto.randomUUID(),conferenceSolutionKey:{type:'hangoutsMeet'}}},reminders:{useDefault:true}};const ev=await google(`/calendars/${encodeURIComponent(CFG.calendarId)}/events?conferenceDataVersion=1&sendUpdates=all`,{method:'POST',body:JSON.stringify(event)});const meetUrl=ev.hangoutLink||ev?.conferenceData?.entryPoints?.find(x=>x.entryPointType==='video')?.uri||null;return res.status(200).json({ok:true,start:start.toISOString(),meetUrl,eventUrl:ev.htmlLink||null,supportEmail:CFG.support});
}catch(e){console.error('Schedule API',e);return res.status(e?.code==='CONFIG'?503:502).json({error:e?.code==='CONFIG'?'Online scheduling is being configured. Please contact us by email.':'Unable to access the calendar right now. Please try again.'})}}